export default {
  pluginId: 'iximei/crm',
  dbNamespace: 'iximei_crm',
  name: 'crm',
  // CRM 页面在业务产品中作为一级菜单展示，不生成插件目录菜单。
  menuRoot: false,
  version: '1.0.0',
  coreCompatibility: '^1.0.0',
  channels: ['admin'],
  // Keep this aligned with the module autoload prefix in src/app.ts.
  routeBase: '/api/modules/crm/v1',
  icon: 'customer-service',
  permissions: [
    { code: 'crm:hospital:list', label: '医院管理-列表', group: 'crm' },
    { code: 'crm:hospital:create', label: '医院管理-创建', group: 'crm' },
    { code: 'crm:hospital:update', label: '医院管理-更新', group: 'crm' },
    { code: 'crm:hospital:delete', label: '医院管理-删除', group: 'crm' },
    { code: 'crm:customer:list', label: '客户管理-列表', group: 'crm' },
    { code: 'crm:customer:create', label: '客户管理-创建', group: 'crm' },
    { code: 'crm:customer:update', label: '客户管理-更新', group: 'crm' },
    { code: 'crm:customer:dispatch', label: '客户管理-派单', group: 'crm' },
    { code: 'crm:member:list', label: '会员顾客-列表', group: 'crm' },
    { code: 'crm:member:create', label: '会员顾客-创建', group: 'crm' },
    { code: 'crm:member:update', label: '会员顾客-更新', group: 'crm' },
    { code: 'crm:member:remark', label: '会员顾客-备注', group: 'crm' },
    { code: 'crm:dispatch:list', label: '派单管理-列表', group: 'crm' },
    { code: 'crm:dispatch:update', label: '派单管理-更新', group: 'crm' },
    { code: 'crm:dispatch:reply', label: '派单管理-回复', group: 'crm' },
    { code: 'crm:dispatch:log', label: '派单管理-跟进', group: 'crm' },
    { code: 'crm:region:list', label: '地区-列表', group: 'crm' },
  ],
  menus: [
    { channel: 'admin', path: '/plugins/iximei/crm/hospitals', name: '医院管理', perm: 'crm:hospital:list', icon: 'hospital' },
    { channel: 'admin', path: '/plugins/iximei/crm/customers', name: '客户管理', perm: 'crm:customer:list', icon: 'users-round' },
    { channel: 'admin', path: '/plugins/iximei/crm/members', name: '会员顾客', perm: 'crm:member:list', icon: 'contact-round' },
    { channel: 'admin', path: '/plugins/iximei/crm/dispatches', name: '派单管理', perm: 'crm:dispatch:list', icon: 'clipboard-list' },
    { channel: 'admin', path: '/plugins/iximei/crm/dispatches/reply', name: '派单回复', perm: 'crm:dispatch:reply', hideInMenu: true },
  ],
} as const;
