export default {
  pluginId: 'yishan/portal',
  name: 'portal',
  menuRootName: '门户管理',
  menuRootSort: 20,
  version: '1.0.0',
  coreCompatibility: '^1.0.0',
  channels: ['admin'],
  routeBase: '/api/modules/yishan/portal/v1',
  icon: 'read',
  permissions: [
    'portal:article:list',
    'portal:article:create',
    'portal:page:list',
    'portal:page:create',
    'portal:post:list',
    'portal:post:create',
  ],
  menus: [
    { channel: 'admin', path: '/plugins/yishan/portal/articles', name: '文章管理', perm: 'portal:article:list', icon: 'read' },
    { channel: 'admin', path: '/plugins/yishan/portal/pages', name: '页面管理', perm: 'portal:page:list', icon: 'appstore' },
    { channel: 'admin', path: '/plugins/yishan/portal/categories', name: '分类管理', perm: 'portal:article:list', icon: 'appstore' },
    { channel: 'admin', path: '/plugins/yishan/portal/article-templates', name: '文章模板', perm: 'portal:article:list', icon: 'appstore' },
    { channel: 'admin', path: '/plugins/yishan/portal/page-templates', name: '页面模板', perm: 'portal:page:list', icon: 'appstore' },
  ],
} as const;
