edition: 3.0.0
name: yishan-runner
access: "enterprise"
vars:
  region: ${env(FUNCTION_REGION)}
  functionName: ${env(FUNCTION_NAME)}
resources:
  yishan_runner:
    component: fc3
    props:
      region: ${vars.region}
      description: ${env(FUNCTION_DESCRIPTION)}
      runtime: custom.debian12
      handler: infrastructure/migrations/runner.handler
      timeout: 600
      cpu: 1
      memorySize: 1024
      diskSize: 512
      vpcConfig:
        vpcId: ${env(FUNCTION_VPC_ID)}
        vSwitchIds:
          - ${env(FUNCTION_VSWITCH_ID)}
        securityGroupId: ${env(FUNCTION_SECURITY_GROUP)}
      environmentVariables:
        NODE_ENV: production
        PATH: /var/fc/lang/nodejs22/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/code:/code/bin
        NODE_PATH: /code/node_modules
        LD_LIBRARY_PATH: /code:/code/lib:/usr/lib:/opt/lib:/usr/local/lib
        DATABASE_USER: ${env(DATABASE_USER)}
        DATABASE_PASSWORD: ${env(DATABASE_PASSWORD)}
        DATABASE_NAME: ${env(DATABASE_NAME)}
        DATABASE_HOST: ${env(DATABASE_HOST)}
        DATABASE_PORT: ${env(DATABASE_PORT)}
        ALLOW_PRODUCTION_SEED: ${env(ALLOW_PRODUCTION_SEED)}
        SEED_ADMIN_PASSWORD: ${env(SEED_ADMIN_PASSWORD)}
      functionName: ${vars.functionName}
      code: ../.build/function-code
      customRuntimeConfig:
        command:
          - node
          - ./infrastructure/migrations/server.js
        port: 3000
