import { type FastifyPluginAsync } from 'fastify'
import { createRouteRegistrar } from '@/core/routes/route-registrar.js'
import { ResponseUtil } from '@/utils/response.js'
import { ContractService } from '../../../services/contract.service.js'
import { ContractCreateReqSchema, ContractIdParamSchema, ContractListQuerySchema, ContractRespSchema, ContractUpdateReqSchema } from '../../../schemas/contract.schema.js'
import { EnvelopeSchema, OkEnvelopeSchema, PaginatedEnvelopeSchema, ROUTE_TAG } from '../../../schemas/routes.schema.js'
import { CrmPermissions as PERMS } from '../../../schemas/permissions.js'
export default (async (app) => { const route = createRouteRegistrar(app); const service = new ContractService()
  route.get('/', { access: { permission: PERMS.CONTRACT_LIST }, schema: { tags: [ROUTE_TAG], querystring: ContractListQuerySchema, response: { 200: PaginatedEnvelopeSchema(ContractRespSchema) } } }, async (request: any, reply: any) => { const result = await service.list(request.query, request.currentUser); return ResponseUtil.paginated(reply, result.items, result.page, result.pageSize, result.total) })
  route.post('/', { access: { permission: PERMS.CONTRACT_CREATE }, schema: { tags: [ROUTE_TAG], body: ContractCreateReqSchema, response: { 200: EnvelopeSchema(ContractRespSchema) } } }, async (request: any, reply: any) => ResponseUtil.success(reply, await service.create({ ...request.body, signedAt: request.body.signedAt ? new Date(request.body.signedAt) : null, effectiveAt: request.body.effectiveAt ? new Date(request.body.effectiveAt) : null, expiresAt: request.body.expiresAt ? new Date(request.body.expiresAt) : null, status: request.body.status ?? 'draft', ownerUserId: request.currentUser.id, ownerDepartmentId: request.currentUser.deptIds?.[0] ?? null, attachmentIds: null, description: request.body.description ?? null }, request.currentUser)))
  route.get('/:id', { access: { permission: PERMS.CONTRACT_LIST }, schema: { tags: [ROUTE_TAG], params: ContractIdParamSchema, response: { 200: EnvelopeSchema(ContractRespSchema) } } }, async (request: any, reply: any) => ResponseUtil.success(reply, await service.detail(request.params.id, request.currentUser)))
  route.patch('/:id', { access: { permission: PERMS.CONTRACT_UPDATE }, schema: { tags: [ROUTE_TAG], params: ContractIdParamSchema, body: ContractUpdateReqSchema, response: { 200: EnvelopeSchema(ContractRespSchema) } } }, async (request: any, reply: any) => ResponseUtil.success(reply, await service.update(request.params.id, request.body, request.currentUser)))
  route.delete('/:id', { access: { permission: PERMS.CONTRACT_DELETE }, schema: { tags: [ROUTE_TAG], params: ContractIdParamSchema, response: { 200: OkEnvelopeSchema } } }, async (request: any, reply: any) => { await service.remove(request.params.id, request.currentUser); return ResponseUtil.success(reply, null) })
}) as FastifyPluginAsync
