import { request } from '@umijs/max';
const base = '/api/modules/crm/v1/admin';
const get = (path: string, params?: any) => request(`${base}${path}`, { method: 'GET', params });
const post = (path: string, data?: any) => request(`${base}${path}`, { method: 'POST', data });
const put = (path: string, data?: any) => request(`${base}${path}`, { method: 'PUT', data });
const del = (path: string) => request(`${base}${path}`, { method: 'DELETE' });
export const getHospitals = (params?: any) => get('/hospitals/', params);
export const getHospital = (id: number) => get(`/hospitals/${id}`);
export const createHospital = (data: any) => post('/hospitals/', data);
export const updateHospital = (id: number, data: any) => put(`/hospitals/${id}`, data);
export const deleteHospital = (id: number) => del(`/hospitals/${id}`);
export const searchHospitals = (params?: any) => get('/hospitals/search/options', params);
export const getHospitalAccounts = (id: number) => get(`/hospitals/${id}/accounts`);
export const createHospitalAccount = (id: number, data: any) => post(`/hospitals/${id}/accounts`, data);
export const assignHospitalAccount = (id: number, data: any) => post(`/hospitals/${id}/accounts/assign`, data);
export const updateHospitalAccount = (id: number, userId: number, data: any) => put(`/hospitals/${id}/accounts/${userId}`, data);
export const deleteHospitalAccount = (id: number, userId: number) => del(`/hospitals/${id}/accounts/${userId}`);
export const getCustomerStatuses = () => get('/customers/statuses');
export const getCustomers = (params?: any) => get('/customers/', params);
export const createCustomer = (data: any) => post('/customers/', data);
export const updateCustomer = (id: number, data: any) => put(`/customers/${id}`, data);
export const dispatchCustomer = (id: number, data: any) => post(`/customers/${id}/dispatch`, data);
export const getMembers = (params?: any) => get('/members/', params);
export const getMember = (id: number) => get(`/members/${id}`);
export const createMember = (data: any) => post('/members/', data);
export const updateMember = (id: number, data: any) => put(`/members/${id}`, data);
export const addMemberRemark = (id: number, data: any) => post(`/members/${id}/remarks`, data);
export const getDispatchStatuses = () => get('/dispatches/statuses');
export const getDispatches = (params?: any) => get('/dispatches/', params);
export const getDispatch = (id: number) => get(`/dispatches/${id}`);
export const updateDispatch = (id: number, data: any) => put(`/dispatches/${id}`, data);
export const addDispatchReply = (id: number, data: any) => post(`/dispatches/${id}/replies`, data);
export const addDispatchLog = (id: number, data: any) => post(`/dispatches/${id}/logs`, data);
