import { Type, type Static } from '@sinclair/typebox'
import { PaginationQuerySchema } from './common.schema.js'

export const OPPORTUNITY_STAGES = ['requirement', 'proposal', 'negotiation', 'won', 'lost'] as const
export type OpportunityStageCode = (typeof OPPORTUNITY_STAGES)[number]
export const opportunityStageConfig = { requirement: { label: '需求确认', probability: 20 }, proposal: { label: '方案报价', probability: 40 }, negotiation: { label: '商务谈判', probability: 70 }, won: { label: '成交', probability: 100 }, lost: { label: '失败', probability: 0 } } as const
export const OPPORTUNITY_STAGE_LABELS = Object.fromEntries(Object.entries(opportunityStageConfig).map(([stage, config]) => [stage, config.label])) as Record<OpportunityStageCode, string>
export const OPPORTUNITY_LOST_REASONS = ['price', 'competitor', 'budget_cancelled', 'demand_cancelled', 'postponed', 'unreachable', 'other'] as const
export type OpportunityLostReason = (typeof OPPORTUNITY_LOST_REASONS)[number]
export const OPPORTUNITY_LOST_REASON_LABELS: Record<OpportunityLostReason, string> = { price: '价格原因', competitor: '竞品成交', budget_cancelled: '预算取消', demand_cancelled: '需求取消', postponed: '暂缓采购', unreachable: '无法联系', other: '其他' }
const StageSchema = Type.Union(OPPORTUNITY_STAGES.map((stage) => Type.Literal(stage)))
const LostReasonSchema = Type.Union(OPPORTUNITY_LOST_REASONS.map((reason) => Type.Literal(reason)))
export const OpportunityProductSchema = Type.Object({ id: Type.Integer(), code: Type.String(), name: Type.String() })
export const OpportunityRespSchema = Type.Object({ id: Type.Integer(), name: Type.String(), customerId: Type.Integer(), primaryContactId: Type.Union([Type.Integer(), Type.Null()]), ownerId: Type.Union([Type.Integer(), Type.Null()]), ownerName: Type.Union([Type.String(), Type.Null()]), ownerDepartmentId: Type.Union([Type.Integer(), Type.Null()]), stage: StageSchema, amountCents: Type.Union([Type.Number(), Type.Null()]), expectedCloseDate: Type.Union([Type.String({ format: 'date-time' }), Type.Null()]), requirement: Type.Union([Type.String(), Type.Null()]), nextAction: Type.Union([Type.String(), Type.Null()]), nextFollowUpAt: Type.Union([Type.String({ format: 'date-time' }), Type.Null()]), remark: Type.Union([Type.String(), Type.Null()]), lostReason: Type.Union([LostReasonSchema, Type.Null()]), products: Type.Array(OpportunityProductSchema), createdAt: Type.String({ format: 'date-time' }), updatedAt: Type.String({ format: 'date-time' }) })
export const OpportunityListQuerySchema = Type.Composite([PaginationQuerySchema, Type.Object({ keyword: Type.Optional(Type.String({ maxLength: 200 })), customerId: Type.Optional(Type.Integer()), primaryContactId: Type.Optional(Type.Integer()), stage: Type.Optional(StageSchema), ownerId: Type.Optional(Type.Integer()) })])
export const OpportunityCreateReqSchema = Type.Object({ name: Type.String({ minLength: 1, maxLength: 200 }), customerId: Type.Integer({ minimum: 1 }), primaryContactId: Type.Optional(Type.Union([Type.Integer(), Type.Null()])), ownerId: Type.Integer({ minimum: 1 }), stage: Type.Optional(Type.Union([Type.Literal('requirement'), Type.Literal('proposal'), Type.Literal('negotiation')])), amountCents: Type.Optional(Type.Union([Type.Integer({ minimum: 0 }), Type.Null()])), expectedCloseDate: Type.Optional(Type.Union([Type.String({ format: 'date-time' }), Type.Null()])), productIds: Type.Optional(Type.Array(Type.Integer({ minimum: 1 }), { uniqueItems: true })), requirement: Type.Optional(Type.String({ maxLength: 2000 })), remark: Type.Optional(Type.String({ maxLength: 500 })), nextAction: Type.Optional(Type.String({ maxLength: 500 })), nextFollowUpAt: Type.Optional(Type.Union([Type.String({ format: 'date-time' }), Type.Null()])) })
export type OpportunityCreateReq = Static<typeof OpportunityCreateReqSchema>
export const OpportunityUpdateReqSchema = Type.Object({ name: Type.Optional(Type.String({ minLength: 1, maxLength: 200 })), primaryContactId: Type.Optional(Type.Union([Type.Integer(), Type.Null()])), ownerId: Type.Optional(Type.Integer({ minimum: 1 })), amountCents: Type.Optional(Type.Union([Type.Integer({ minimum: 0 }), Type.Null()])), expectedCloseDate: Type.Optional(Type.Union([Type.String({ format: 'date-time' }), Type.Null()])), productIds: Type.Optional(Type.Array(Type.Integer({ minimum: 1 }), { uniqueItems: true })), requirement: Type.Optional(Type.Union([Type.String({ maxLength: 2000 }), Type.Null()])), nextAction: Type.Optional(Type.Union([Type.String({ maxLength: 500 }), Type.Null()])), nextFollowUpAt: Type.Optional(Type.Union([Type.String({ format: 'date-time' }), Type.Null()])), remark: Type.Optional(Type.Union([Type.String({ maxLength: 1000 }), Type.Null()])) })
export type OpportunityUpdateReq = Static<typeof OpportunityUpdateReqSchema>
export const OpportunityIdParamSchema = Type.Object({ id: Type.Integer({ minimum: 1 }) })
export const OpportunityAdvanceReqSchema = Type.Object({ toStage: Type.Union([Type.Literal('proposal'), Type.Literal('negotiation')]), reason: Type.Optional(Type.String({ maxLength: 500 })) })
export const OpportunityMarkWonReqSchema = Type.Object({ reason: Type.Optional(Type.String({ maxLength: 500 })) })
export const OpportunityMarkLostReqSchema = Type.Object({ lostReason: LostReasonSchema, reason: Type.Optional(Type.String({ maxLength: 500 })) })
export const OpportunityTransferReqSchema = Type.Object({ ownerId: Type.Integer({ minimum: 1 }), reason: Type.Optional(Type.String({ maxLength: 500 })) })
export type OpportunityAdvanceReq = Static<typeof OpportunityAdvanceReqSchema>
export type OpportunityMarkWonReq = Static<typeof OpportunityMarkWonReqSchema>
export type OpportunityMarkLostReq = Static<typeof OpportunityMarkLostReqSchema>
export type OpportunityTransferReq = Static<typeof OpportunityTransferReqSchema>
