import { definePermissions } from './define-permissions.js';

/** Core module permission registry: the single source for Core code and UI metadata. */
export const corePermissions = definePermissions({
  SYSTEM_USER_LIST: { code: 'system:user:list', label: '用户管理-列表', group: 'system' },
  SYSTEM_USER_CREATE: { code: 'system:user:create', label: '用户管理-创建', group: 'system' },
  SYSTEM_USER_UPDATE: { code: 'system:user:update', label: '用户管理-更新', group: 'system' },
  SYSTEM_USER_DELETE: { code: 'system:user:delete', label: '用户管理-删除', group: 'system' },
  SYSTEM_ROLE_LIST: { code: 'system:role:list', label: '角色管理-列表', group: 'system' },
  SYSTEM_ROLE_CREATE: { code: 'system:role:create', label: '角色管理-创建', group: 'system' },
  SYSTEM_ROLE_UPDATE: { code: 'system:role:update', label: '角色管理-更新', group: 'system' },
  SYSTEM_ROLE_DELETE: { code: 'system:role:delete', label: '角色管理-删除', group: 'system' },
  SYSTEM_ROLE_GRANT: { code: 'system:role:grant', label: '角色管理-授权', group: 'system' },
  SYSTEM_MENU_LIST: { code: 'system:menu:list', label: '菜单管理-列表', group: 'system' },
  SYSTEM_MENU_CREATE: { code: 'system:menu:create', label: '菜单管理-创建', group: 'system' },
  SYSTEM_MENU_UPDATE: { code: 'system:menu:update', label: '菜单管理-更新', group: 'system' },
  SYSTEM_MENU_DELETE: { code: 'system:menu:delete', label: '菜单管理-删除', group: 'system' },
  SYSTEM_DEPARTMENT_LIST: { code: 'system:department:list', label: '部门管理-列表', group: 'system' },
  SYSTEM_DEPARTMENT_CREATE: { code: 'system:department:create', label: '部门管理-创建', group: 'system' },
  SYSTEM_DEPARTMENT_UPDATE: { code: 'system:department:update', label: '部门管理-更新', group: 'system' },
  SYSTEM_DEPARTMENT_DELETE: { code: 'system:department:delete', label: '部门管理-删除', group: 'system' },
  SYSTEM_POSITION_LIST: { code: 'system:position:list', label: '岗位管理-列表', group: 'system' },
  SYSTEM_POSITION_CREATE: { code: 'system:position:create', label: '岗位管理-创建', group: 'system' },
  SYSTEM_POSITION_UPDATE: { code: 'system:position:update', label: '岗位管理-更新', group: 'system' },
  SYSTEM_POSITION_DELETE: { code: 'system:position:delete', label: '岗位管理-删除', group: 'system' },
  SYSTEM_DICT_LIST: { code: 'system:dict:list', label: '字典管理-列表', group: 'system' },
  SYSTEM_DICT_CREATE: { code: 'system:dict:create', label: '字典管理-创建', group: 'system' },
  SYSTEM_DICT_UPDATE: { code: 'system:dict:update', label: '字典管理-更新', group: 'system' },
  SYSTEM_DICT_DELETE: { code: 'system:dict:delete', label: '字典管理-删除', group: 'system' },
  SYSTEM_ATTACHMENT_LIST: { code: 'system:attachment:list', label: '附件管理-列表', group: 'system' },
  SYSTEM_ATTACHMENT_CREATE: { code: 'system:attachment:create', label: '附件管理-创建', group: 'system' },
  SYSTEM_ATTACHMENT_UPDATE: { code: 'system:attachment:update', label: '附件管理-更新', group: 'system' },
  SYSTEM_ATTACHMENT_DELETE: { code: 'system:attachment:delete', label: '附件管理-删除', group: 'system' },
  SYSTEM_PLUGIN_LIST: { code: 'system:plugin:list', label: '插件管理-列表', group: 'system' },
  SYSTEM_PLUGIN_INSTALL: { code: 'system:plugin:install', label: '插件管理-安装', group: 'system' },
  SYSTEM_PLUGIN_ENABLE: { code: 'system:plugin:enable', label: '插件管理-启用', group: 'system' },
  SYSTEM_PLUGIN_DISABLE: { code: 'system:plugin:disable', label: '插件管理-禁用', group: 'system' },
  SYSTEM_PLUGIN_SYNC: { code: 'system:plugin:sync', label: '插件管理-同步', group: 'system' },
  SYSTEM_PLUGIN_AUDIT: { code: 'system:plugin:audit', label: '插件管理-审计', group: 'system' },
  SYSTEM_OPTION_LIST: { code: 'system:option:list', label: '系统选项-列表', group: 'system' },
  SYSTEM_OPTION_UPDATE: { code: 'system:option:update', label: '系统选项-更新', group: 'system' },
  SYSTEM_DASHBOARD_READ: { code: 'system:dashboard:read', label: '仪表盘-读取', group: 'system' },
  SYSTEM_LOGIN_LOG_LIST: { code: 'system:login-log:list', label: '登录日志-列表', group: 'system' },
  SYSTEM_STORAGE_LIST: { code: 'system:storage:list', label: '存储管理-列表', group: 'system' },
  SYSTEM_STORAGE_UPDATE: { code: 'system:storage:update', label: '存储管理-更新', group: 'system' },
  SYSTEM_STORAGE_UPLOAD_TOKEN: { code: 'system:storage:upload-token', label: '存储管理-上传令牌', group: 'system' },
  SYSTEM_TOKEN_LIST: { code: 'system:token:list', label: 'API Token-列表', group: 'system' },
  SYSTEM_TOKEN_CLEANUP: { code: 'system:token:cleanup', label: 'API Token-清理', group: 'system' },
  API_TOKEN_MANAGE: { code: 'system:api-token:manage', label: 'API Token-管理', group: 'system' },
} as const);

export const corePermissionDefinitions: readonly import('./define-permissions.js').PermissionRef[] = Object.values(corePermissions);
