export default {
  pluginId: 'yishan/shop',
  name: 'shop',
  menuRootName: '商城管理',
  menuRootSort: 22,
  version: '1.0.0',
  coreCompatibility: '^1.0.0',
  channels: ['admin'],
  routeBase: '/api/modules/shop/v1',
  icon: 'shopping',
  permissions: [
    'shop:category:list',
    'shop:category:create',
    'shop:category:update',
    'shop:category:delete',
    'shop:attribute:list',
    'shop:attribute:create',
    'shop:attribute:update',
    'shop:attribute:delete',
    'shop:product:list',
    'shop:product:create',
    'shop:product:update',
    'shop:product:delete',
    'shop:sku:list',
    'shop:sku:create',
    'shop:sku:update',
    'shop:sku:delete',
    'shop:order:list',
    'shop:order:update',
    'shop:order:delete',
  ],
  menus: [
    { channel: 'admin', path: '/plugins/yishan/shop/categories', name: '商品分类', perm: 'shop:category:list', icon: 'folder' },
    { channel: 'admin', path: '/plugins/yishan/shop/attributes', name: '商品属性', perm: 'shop:attribute:list', icon: 'appstore' },
    { channel: 'admin', path: '/plugins/yishan/shop/products', name: '商品管理', perm: 'shop:product:list', icon: 'shopping' },
    { channel: 'admin', path: '/plugins/yishan/shop/skus', name: 'SKU管理', perm: 'shop:sku:list', icon: 'inbox' },
    { channel: 'admin', path: '/plugins/yishan/shop/orders', name: '订单管理', perm: 'shop:order:list', icon: 'file-text' },
  ],
} as const;