export * from './client'
export * from './types'
export * as authApi from './auth'
export * as userApi from './user'
export * as menuApi from './menu'
export * as contactsApi from './contacts'
export * as dictApi from './dict'
export * as dashboardApi from './dashboard'
export * from './admin'
