/**
 * 商城模块业务错误码
 */

export enum ShopErrorCode {
  // 通用错误
  SHOP_NOT_FOUND = "SHOP_NOT_FOUND",
  SHOP_PARAM_ERROR = "SHOP_PARAM_ERROR",
  SHOP_STATUS_ERROR = "SHOP_STATUS_ERROR",

  // 商品错误
  PRODUCT_NOT_FOUND = "SHOP_PRODUCT_NOT_FOUND",
  PRODUCT_NAME_DUPLICATE = "SHOP_PRODUCT_NAME_DUPLICATE",
  PRODUCT_STATUS_ERROR = "SHOP_PRODUCT_STATUS_ERROR",
  PRODUCT_STOCK_INSUFFICIENT = "SHOP_PRODUCT_STOCK_INSUFFICIENT",

  // 分类错误
  CATEGORY_NOT_FOUND = "SHOP_CATEGORY_NOT_FOUND",
  CATEGORY_NAME_DUPLICATE = "SHOP_CATEGORY_NAME_DUPLICATE",
  CATEGORY_HAS_PRODUCTS = "SHOP_CATEGORY_HAS_PRODUCTS",

  // SKU错误
  SKU_NOT_FOUND = "SHOP_SKU_NOT_FOUND",
  SKU_CODE_DUPLICATE = "SHOP_SKU_CODE_DUPLICATE",
  SKU_STOCK_INSUFFICIENT = "SHOP_SKU_STOCK_INSUFFICIENT",

  // 属性错误
  ATTRIBUTE_NOT_FOUND = "SHOP_ATTRIBUTE_NOT_FOUND",
  ATTRIBUTE_HAS_SKUS = "SHOP_ATTRIBUTE_HAS_SKUS",

  // 订单错误
  ORDER_NOT_FOUND = "SHOP_ORDER_NOT_FOUND",
  ORDER_STATUS_ERROR = "SHOP_ORDER_STATUS_ERROR",
  ORDER_ITEM_ERROR = "SHOP_ORDER_ITEM_ERROR",
  ORDER_PAY_STATUS_ERROR = "SHOP_ORDER_PAY_STATUS_ERROR",

  // 购物车错误
  CART_NOT_FOUND = "SHOP_CART_NOT_FOUND",
  CART_PRODUCT_NOT_FOUND = "SHOP_CART_PRODUCT_NOT_FOUND",
  CART_SKU_NOT_FOUND = "SHOP_CART_SKU_NOT_FOUND",

  // 地址错误
  ADDRESS_NOT_FOUND = "SHOP_ADDRESS_NOT_FOUND",
  ADDRESS_NOT_DEFAULT = "SHOP_ADDRESS_NOT_DEFAULT",
}
