/**
 * plugin.ts — Admin 唯一模块扩展点
 *
 * 编译期扫描 Core 与 modules 页面，生成 src/.umi/module-components.ts，
 * 提供 `moduleComponentsMap`：key 形如 `./system/user` / `./modules/demo/todos`，
 * value 是动态 `import()` 的 Promise 工厂。
 *
 * 为什么不用 `require.context`：
 *   Umi 当前集成的 Mako 0.11.10 不会把 `require.context(...)` 转成 virtual 模块，
 *   浏览器运行时会抛 `require.context is only available in Mako/webpack bundler runtime`。
 *   改用 Umi 插件的 `onGenerateFiles` 在编译期把页面路径全部列出，
 *   运行时通过 `import('./core/...')` 与 `import('./modules/...')` 真正加载。
 */

import { join } from 'node:path'
import { existsSync, readdirSync, statSync } from 'node:fs'
import type { IApi } from '@umijs/max'

const PAGES_DIR = 'src/pages'
const MODULES_DIR = 'src/modules'

/** 递归收集 `<dir>/<page>/index.tsx` 形式的页面，path 为相对项目的虚拟路径（./xxx/yyy）。 */
function collectPages(absDir: string, prefix: string): string[] {
  if (!existsSync(absDir)) return []
  const out: string[] = []
  const walk = (cur: string, parts: string[]) => {
    const entries = readdirSync(cur)
    const hasIndex = entries.includes('index.tsx')
    for (const name of entries) {
      const full = join(cur, name)
      const st = statSync(full)
      if (st.isDirectory()) {
        walk(full, [...parts, name])
      }
    }
    if (hasIndex) {
      // parts 空 → 当前就是 src/pages 根 → key 必须是 './index'（与 routes.ts / sys_menu.component 约定一致）
      const virtual = parts.length === 0 ? './index' : prefix + parts.join('/')
      out.push(virtual)
    }
  }
  walk(absDir, [])
  return out
}

function genModuleComponentsFile(): string {
  const projectRoot = process.cwd()
  const coreAbs = join(projectRoot, PAGES_DIR)
  const moduleAbs = join(projectRoot, MODULES_DIR)

  const coreKeys = collectPages(coreAbs, './')
  const moduleKeys: Array<{ key: string; moduleId: string; page: string }> = []
  if (existsSync(moduleAbs)) {
    for (const moduleId of readdirSync(moduleAbs)) {
      const moduleDir = join(moduleAbs, moduleId)
      if (!statSync(moduleDir).isDirectory()) continue
      const pagesDir = join(moduleDir, 'pages')
      if (!existsSync(pagesDir)) continue
      for (const page of readdirSync(pagesDir)) {
        const full = join(pagesDir, page, 'index.tsx')
        if (!existsSync(full)) continue
        moduleKeys.push({
          key: `./modules/${moduleId}/${page}`,
          moduleId,
          page,
        })
      }
    }
  }

  const entries: string[] = []
  for (const k of coreKeys) {
    // k = './system/user' → import path '@pages/system/user' (实际物理位置 src/pages/system/user/index.tsx)
    const imp = `@/pages${k.slice(1)}`
    entries.push(`  ${JSON.stringify(k)}: () => import(${JSON.stringify(imp)})`)
  }
  for (const m of moduleKeys) {
    // './modules/demo/todos' → '@/modules/demo/pages/todos'
    const imp = `@/modules/${m.moduleId}/pages/${m.page}`
    entries.push(`  ${JSON.stringify(m.key)}: () => import(${JSON.stringify(imp)})`)
  }

  return `// @ts-nocheck
/* eslint-disable */
// Auto-generated by apps/yishan-admin/plugin.ts. Do not edit.

export const moduleComponentsMap: Record<string, () => Promise<any>> = Object.freeze({
${entries.join(',\n')}
})
`
}

export default (api: IApi) => {
  api.describe({ key: 'admin-module-components' })

  api.onGenerateFiles(() => {
    // 直接写根 .umi 目录，避免被 Umi 套到 plugin-<key>/ 子目录里。
    // writeTmpFile 不允许写到根；改用 pluginAPI 提供的 paths + 写文件。
    const fs = require('node:fs')
    const path = require('node:path')
    const target = path.join(api.paths.absTmpPath, 'module-components.ts')
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, genModuleComponentsFile(), 'utf-8')
  })

  api.addTmpGenerateWatcherPaths(() => [
    join(api.paths.absSrcPath ?? join(process.cwd(), 'src'), 'pages'),
    join(api.paths.absSrcPath ?? join(process.cwd(), 'src'), 'modules'),
  ])
}
