edition: 3.0.0
name: yishan-demo-layered-domain
access: "enterprise"
vars:
  region: "cn-shanghai"
  functionName: ${env(FC_FUNCTION_NAME)}
  customDomain: ${env(FC_CUSTOM_DOMAIN)}
  certName: ${env(FC_CERT_NAME)}
resources:
  yishan_demo_layered_domain:
    component: fc3-domain
    props:
      region: ${vars.region}
      domainName: ${vars.customDomain}
      protocol: HTTPS
      certConfig:
        certName: ${vars.certName}
        certificate: ${file(./deploy/fc3/certs/fullchain.cer)}
        privateKey: ${file(./deploy/fc3/certs/private.key)}
      routeConfig:
        routes:
          - path: /*
            functionName: ${vars.functionName}
